version: '3'

services:

  db:
    build: mariadb
    image: wetoday_db:1.0
    container_name: wetoday_db
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: team
      MYSQL_DATABASE: wetoday
      MYSQL_USER: team
      MYSQL_PASSWORD: team

volumes:
  db-data:
